### ISSUE TITLE
Adding holdingbranch

### ISSUE THREAD

**Issue by Draky50110** [DSI-Universite-Rennes2/koha-unquarantine#2]
Hello.

Is it possible to add "holdingbranch" to have the script running with a third parameter like "script status days holdingbranch" and if no third parameter, all sites ?

We have 3 libraries and not same days of getting books back to shelves ;)

Thanks.

**Comment by jsicot** [comment]
Hello @Draky50110,

Thank you for this enhancement request.
I have added a new parameter "quarantinebranch [qb]" that allows filtering on a specific holdingbranch.
Now, you can execute the script several times in your crontab by playing with the 3 params.

Example :
0 1 * * * perl /path/to/unquarantine.pl 9 3 BRANCH1
0 1 * * * perl /path/to/unquarantine.pl 9 4 BRANCH2
0 1 * * * perl /path/to/unquarantine.pl 9 5 BRANCH3

A little warning, before this last commit, the script was looking for items with quarantine status for which the return date was lower or equal to the current date less the quarantine period, now it retrieves items with a return date equal to the current date less the quarantine period.

Best,
Julien

**Comment by Draky50110** [comment]
Wow thanks a lot :)

Great great improvments :)
